In [55]:
import pandas as pd

In [56]:
df = pd.read_csv('C:/Users/USER/DA_Projects/NASA-Asteroids-Classification/Asteroids.csv')

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4687 entries, 0 to 4686
Data columns (total 42 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   neo_reference_id                                             4687 non-null   int64
 1   name                                                         4687 non-null   object
 2   nasa_jpl_url                                                 4687 non-null   object
 3   absolute_magnitude_h                                         4687 non-null   float64
 4   is_potentially_hazardous_asteroid                            4687 non-null   bool
 5   links.self                                                   4687 non-null   object
 6   estimated_diameter.kilometers.estimated_diameter_min         4687 non-null   float64
 7   estimated_diameter.kilometers.estimated_diameter_max         4687 non-null   float64
 8   estimated_diameter.meters.estimated_diameter_min             4687 non-null   float64
 9   estimated_diameter.meters.estimated_diameter_max             4687 non-null   float64
 10  estimated_diameter.miles.estimated_diameter_min              4687 non-null   float64
 11  estimated_diameter.miles.estimated_diameter_max              4687 non-null   float64
 12  estimated_diameter.feet.estimated_diameter_min               4687 non-null   float64
 13  estimated_diameter.feet.estimated_diameter_max               4687 non-null   float64
 14  close_approach_data.close_approach_date                      4687 non-null   object
 15  close_approach_data.epoch_date_close_approach                4687 non-null   int64
 16  close_approach_data.relative_velocity.kilometers_per_second  4687 non-null   float64
 17  close_approach_data.relative_velocity.kilometers_per_hour    4687 non-null   float64
 18  close_approach_data.relative_velocity.miles_per_hour         4687 non-null   float64
 19  close_approach_data.miss_distance.astronomical               4687 non-null   float64
 20  close_approach_data.miss_distance.lunar                      4687 non-null   float64
 21  close_approach_data.miss_distance.kilometers                 4687 non-null   float64
 22  close_approach_data.miss_distance.miles                      4687 non-null   float64
 23  close_approach_data.orbiting_body                            4687 non-null   object
 24  orbital_data.orbit_id                                        4687 non-null   int64
 25  orbital_data.orbit_determination_date                        4687 non-null   object
 26  orbital_data.orbit_uncertainty                               4687 non-null   int64
 27  orbital_data.minimum_orbit_intersection                      4687 non-null   float64
 28  orbital_data.jupiter_tisserand_invariant                     4687 non-null   float64
 29  orbital_data.epoch_osculation                                4687 non-null   float64
 30  orbital_data.eccentricity                                    4687 non-null   float64
 31  orbital_data.semi_major_axis                                 4687 non-null   float64
 32  orbital_data.inclination                                     4687 non-null   float64
 33  orbital_data.ascending_node_longitude                        4687 non-null   float64
 34  orbital_data.orbital_period                                  4687 non-null   float64
 35  orbital_data.perihelion_distance                             4687 non-null   float64
 36  orbital_data.perihelion_argument                             4687 non-null   float64
 37  orbital_data.aphelion_distance                               4687 non-null   float64
 38  orbital_data.perihelion_time                                 4687 non-null   float64
 39  orbital_data.mean_anomaly                                    4687 non-null   float64
 40  orbital_data.mean_motion                                     4687 non-null   float64
 41  orbital_data.equinox                                         4687 non-null   object
dtypes: bool(1), float64(30), int64(4), object(7)
memory usage: 1.5+ MB

In [58]:
#remove unnecessary columns
df.drop('nasa_jpl_url', inplace = True, axis = 1)
df.drop('links.self', inplace = True, axis = 1)

In [59]:
#rename columns 
df.columns = ['neo_reference_id','name', 'absolute_magnitude_h', 'hazardous', 'est_dia_min(km)', 'est_dia_max(km)',
              'est_dia_min(m)', 'est_dia_max(m)', 'est_dia_min(miles)', 'est_dia_max(miles)', 'est_dia_min(feet)', 
              'est_dia_max(feet)', 'close_approach_date', 'epoch_date_close_approach', 'relative_velocity(km/s)', 
              'relative_velocity(km/h)', 'relative_velocity(miles/h)', 'miss_distance(astronomical)', 'miss_distance(lunar)',
              'miss_distance(km)', 'miss_distance(miles)', 'orbiting_body', 'orbit_id', 'orbit_determination_date', 'orbit_uncertainty',
              'minimum_orbit_intersection', 'jupiter_tisserand_invariant', 'epoch_osculation', 'eccentricity', 'semi_major_axis', 'inclination',
              'ascending_node_longitude', 'orbital_period', 'perihelion_distance', 'perihelion_argument', 'aphelion_distance', 'perihelion_time',
              'mean_anomaly', 'mean_motion', 'equinox']

In [60]:
df

,neo_reference_id,name,absolute_magnitude_h,hazardous,est_dia_min(km),est_dia_max(km),est_dia_min(m),est_dia_max(m),est_dia_min(miles),est_dia_max(miles),...,inclination,ascending_node_longitude,orbital_period,perihelion_distance,perihelion_argument,aphelion_distance,perihelion_time,mean_anomaly,mean_motion,equinox
0,3703080,(2014 YW34),21.600,True,0.127220,0.284472,127.219879,284.472297,0.079051,0.176763,...,6.025981,314.373913,609.599786,0.808259,57.257470,2.005764,2.458162e+06,264.837533,0.590551,J2000
1,3723955,(2015 NK3),21.300,False,0.146068,0.326618,146.067964,326.617897,0.090762,0.202951,...,28.412996,136.717242,425.869294,0.718200,313.091975,1.497352,2.457795e+06,173.741112,0.845330,J2000
2,2446862,446862 (2001 VB76),20.300,True,0.231502,0.517654,231.502122,517.654482,0.143849,0.321655,...,4.237961,259.475979,643.580228,0.950791,248.415038,1.966857,2.458120e+06,292.893654,0.559371,J2000
3,3092506,(2001 WJ4),27.400,False,0.008801,0.019681,8.801465,19.680675,0.005469,0.012229,...,7.905894,57.173266,514.082140,0.983902,18.707701,1.527904,2.457902e+06,68.741007,0.700277,J2000
4,3514799,(2010 FH81),21.600,True,0.127220,0.284472,127.219879,284.472297,0.079051,0.176763,...,16.793382,84.629307,495.597821,0.967687,158.263596,1.483543,2.457814e+06,135.142133,0.726395,J2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4682,3759007,(2016 RQ17),23.900,False,0.044112,0.098637,44.111820,98.637028,0.027410,0.061290,...,39.880491,164.183305,457.179984,0.741558,276.395697,1.581299,2.457708e+06,304.306025,0.787436,J2000
4683,3759295,(2016 RN20),28.200,False,0.006089,0.013616,6.089126,13.615700,0.003784,0.008460,...,5.360249,345.225230,407.185767,0.996434,42.111064,1.153835,2.458088e+06,282.978786,0.884117,J2000
4684,3759714,(2016 SE1),22.700,False,0.076658,0.171412,76.657557,171.411509,0.047633,0.106510,...,4.405467,37.026468,690.054279,0.965760,274.692712,2.090708,2.458300e+06,203.501147,0.521698,J2000
4685,3759720,(2016 SV1),21.800,False,0.116026,0.259442,116.025908,259.441818,0.072095,0.161210,...,21.080244,163.802910,662.048343,1.185467,180.346090,1.787733,2.458288e+06,203.524965,0.543767,J2000
4686,3772978,(2017 FE101),19.109,False,0.400641,0.895860,400.640618,895.859655,0.248946,0.556661,...,53.574923,187.642183,653.679098,0.876110,222.436688,2.071980,2.458319e+06,184.820424,0.550729,J2000

In [61]:
#move column 'hazardous' (target) and apeend it to the end.
df = df[[c for c in df if c not in ['hazardous']] 
       + ['hazardous']]

In [62]:
df

,neo_reference_id,name,absolute_magnitude_h,est_dia_min(km),est_dia_max(km),est_dia_min(m),est_dia_max(m),est_dia_min(miles),est_dia_max(miles),est_dia_min(feet),...,ascending_node_longitude,orbital_period,perihelion_distance,perihelion_argument,aphelion_distance,perihelion_time,mean_anomaly,mean_motion,equinox,hazardous
0,3703080,(2014 YW34),21.600,0.127220,0.284472,127.219879,284.472297,0.079051,0.176763,417.388066,...,314.373913,609.599786,0.808259,57.257470,2.005764,2.458162e+06,264.837533,0.590551,J2000,True
1,3723955,(2015 NK3),21.300,0.146068,0.326618,146.067964,326.617897,0.090762,0.202951,479.225620,...,136.717242,425.869294,0.718200,313.091975,1.497352,2.457795e+06,173.741112,0.845330,J2000,False
2,2446862,446862 (2001 VB76),20.300,0.231502,0.517654,231.502122,517.654482,0.143849,0.321655,759.521423,...,259.475979,643.580228,0.950791,248.415038,1.966857,2.458120e+06,292.893654,0.559371,J2000,True
3,3092506,(2001 WJ4),27.400,0.008801,0.019681,8.801465,19.680675,0.005469,0.012229,28.876199,...,57.173266,514.082140,0.983902,18.707701,1.527904,2.457902e+06,68.741007,0.700277,J2000,False
4,3514799,(2010 FH81),21.600,0.127220,0.284472,127.219879,284.472297,0.079051,0.176763,417.388066,...,84.629307,495.597821,0.967687,158.263596,1.483543,2.457814e+06,135.142133,0.726395,J2000,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4682,3759007,(2016 RQ17),23.900,0.044112,0.098637,44.111820,98.637028,0.027410,0.061290,144.723824,...,164.183305,457.179984,0.741558,276.395697,1.581299,2.457708e+06,304.306025,0.787436,J2000,False
4683,3759295,(2016 RN20),28.200,0.006089,0.013616,6.089126,13.615700,0.003784,0.008460,19.977449,...,345.225230,407.185767,0.996434,42.111064,1.153835,2.458088e+06,282.978786,0.884117,J2000,False
4684,3759714,(2016 SE1),22.700,0.076658,0.171412,76.657557,171.411509,0.047633,0.106510,251.501180,...,37.026468,690.054279,0.965760,274.692712,2.090708,2.458300e+06,203.501147,0.521698,J2000,False
4685,3759720,(2016 SV1),21.800,0.116026,0.259442,116.025908,259.441818,0.072095,0.161210,380.662441,...,163.802910,662.048343,1.185467,180.346090,1.787733,2.458288e+06,203.524965,0.543767,J2000,False
4686,3772978,(2017 FE101),19.109,0.400641,0.895860,400.640618,895.859655,0.248946,0.556661,1314.437764,...,187.642183,653.679098,0.876110,222.436688,2.071980,2.458319e+06,184.820424,0.550729,J2000,False

In [63]:
df.columns

Index(['neo_reference_id', 'name', 'absolute_magnitude_h', 'est_dia_min(km)',
       'est_dia_max(km)', 'est_dia_min(m)', 'est_dia_max(m)',
       'est_dia_min(miles)', 'est_dia_max(miles)', 'est_dia_min(feet)',
       'est_dia_max(feet)', 'close_approach_date', 'epoch_date_close_approach',
       'relative_velocity(km/s)', 'relative_velocity(km/h)',
       'relative_velocity(miles/h)', 'miss_distance(astronomical)',
       'miss_distance(lunar)', 'miss_distance(km)', 'miss_distance(miles)',
       'orbiting_body', 'orbit_id', 'orbit_determination_date',
       'orbit_uncertainty', 'minimum_orbit_intersection',
       'jupiter_tisserand_invariant', 'epoch_osculation', 'eccentricity',
       'semi_major_axis', 'inclination', 'ascending_node_longitude',
       'orbital_period', 'perihelion_distance', 'perihelion_argument',
       'aphelion_distance', 'perihelion_time', 'mean_anomaly', 'mean_motion',
       'equinox', 'hazardous'],
      dtype='object')

In [64]:
#transform 'hazardous' labels true and false to the binary 1 and 0. ie, 1 -> true, 0 -> false
df['hazardous'].replace({True : 1, False : 0}, inplace = True)

C:\Users\USER\Anaconda3\lib\site-packages\pandas\core\generic.py:6610: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [65]:
df['hazardous'].values

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [66]:
df['orbiting_body'].value_counts()

Earth    4687
Name: orbiting_body, dtype: int64

In [67]:
df['equinox'].value_counts()
#Both 'orbiting_body', and 'equinox' have single value. so those are not helpful for our model

J2000    4687
Name: equinox, dtype: int64

In [68]:
#1. neo_reference_id, name and orbit_id are not needed for our model, since they are used by the researchers for identifying the asteroids or orbit.
#2. few of the columns among are same measures, but in different standards.
    #est_dia_min, est_dia_max, relative_velocity, miss_distance and close_approach_date and epoch_date_close_approach
    #reserve one column from each measure and drop the remainings.
# 3. drop 'orbiting_body' and 'equinox' due to their single value.
#let's drop those columns

df.drop(['neo_reference_id', 'name', 'orbit_id', 'est_dia_min(m)', 'est_dia_max(m)', 'est_dia_min(miles)', 
                'est_dia_max(miles)', 'est_dia_min(feet)', 'est_dia_max(feet)', 'epoch_date_close_approach', 'relative_velocity(km/s)',
                'relative_velocity(miles/h)', 'miss_distance(astronomical)', 'miss_distance(lunar)', 'miss_distance(miles)',
               'orbiting_body', 'equinox'], axis = 1, inplace = True)

C:\Users\USER\Anaconda3\lib\site-packages\pandas\core\frame.py:4908: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [69]:
df.columns

Index(['absolute_magnitude_h', 'est_dia_min(km)', 'est_dia_max(km)',
       'close_approach_date', 'relative_velocity(km/h)', 'miss_distance(km)',
       'orbit_determination_date', 'orbit_uncertainty',
       'minimum_orbit_intersection', 'jupiter_tisserand_invariant',
       'epoch_osculation', 'eccentricity', 'semi_major_axis', 'inclination',
       'ascending_node_longitude', 'orbital_period', 'perihelion_distance',
       'perihelion_argument', 'aphelion_distance', 'perihelion_time',
       'mean_anomaly', 'mean_motion', 'hazardous'],
      dtype='object')

In [70]:
df.to_csv('asteroid_data_cleaned.csv', index = False)